<a href="https://colab.research.google.com/github/camilafaiza26/kelompok8_apm/blob/main/GaussianNaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:
#importing the data
dataset = pd.read_csv('lung_cancer.csv')
feature_cols = ['Age', 'Smokes', 'AreaQ', 'Alkhol']
X = dataset[feature_cols].values
y = dataset['Result'].values

In [30]:
#taking a look at the data
dataset.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [35]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [36]:
y_pred  =  classifier.predict(X_test)

In [37]:
y_pred  

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0])

In [38]:
y_test

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0])

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

print (cm)
print (ac)

[[8 0]
 [0 4]]
1.0
