<a href="https://colab.research.google.com/github/camilafaiza26/kelompok8_apm/blob/main/SVM_Non_Linear_Kernel_Polynomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [16]:
#Input Dataset
df = pd.read_csv('glass.csv')
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [17]:
X = df.drop('Type', axis=1)
y = df['Type']

# import package model selection dari Sklearn train_test_split untuk membagi data
from sklearn.model_selection import train_test_split

# membagi data dengan perbandingan data train dan data test 80%:20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.20)


In [18]:
#Membuat fungsi polinomial kernel dengan memberikan nilai untuk parameter degree nya pada kelas svc. 
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly',degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [19]:
#Membuat prediksi pada data uji 
y_pred = svclassifier.predict(X_test)

In [21]:
#Membuat evaluasi untuk polinomial kernel 
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[12  0  0  0  0  0]
 [18  1  0  0  0  0]
 [ 3  0  0  0  0  0]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0  1]
 [ 2  0  0  0  0  5]]
              precision    recall  f1-score   support

           1       0.34      1.00      0.51        12
           2       0.50      0.05      0.10        19
           3       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.83      0.71      0.77         7

    accuracy                           0.42        43
   macro avg       0.28      0.29      0.23        43
weighted avg       0.45      0.42      0.31        43



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
